# -*- mode: ruby -*-
# vi: set ft=ruby :

# # Vagrant 1.7+ automatically inserts a different
# # insecure keypair for each new VM created. The easiest way
# # to use the same keypair for all the machines is to disable
# # this feature and rely on the legacy insecure key.
# # config.ssh.insert_key = false
Vagrant.configure("2") do |config|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/trusty64"

    # Common domain configuration
    config.vm.provider "virtualbox" do |domain|
	domain.customize ["modifyvm", :id, "--nic2", "hostonly"]
        domain.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet1"]
    end

    # Machine-balancer specific definition
    config.vm.define :d1Balancer do |vmconfig|
        vmconfig.vm.hostname = "d1Balancer"
        vmconfig.vm.network :private_network, ip: "172.16.76.2"
	vmconfig.vm.network :forwarded_port, host: 8180,  guest: 80 		# This is the HTTPD load balancer VM for this domain 
        vmconfig.vm.network :forwarded_port, host: 10122, guest: 22, id: "ssh"	# This avoid SSH overlaping port in the host 
	vmconfig.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", "2048"]
  	    vbox.customize ["modifyvm", :id, "--name"  , "d1Balancer"]
        end
        vmconfig.vm.provision :shell, path: "bootstrap.sh"			# Install HTTPD via shell provisioning
    end

    # Machine-nodes specific definition
    (1..2).each do |i|
	config.vm.define "d1Node#{i}" do |vmconfig|
            vmconfig.vm.hostname = "d1Node#{i}"
            vmconfig.vm.network :private_network, ip: "172.16.76.#{2+i}"
            vmconfig.vm.network :forwarded_port, host: "1012#{2+i}", guest: 22, id: "ssh"  # This avoid SSH overlaping port in the host
            vmconfig.vm.provider "virtualbox" do |vbox|
            	vbox.customize ["modifyvm", :id, "--memory", "2048"]
            	vbox.customize ["modifyvm", :id, "--name"  , "d1Node#{i}"]
            end
        end
    end

    # Put the VM Box in Vagrant Cache for future references
    if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
    end
end
