# -*- mode: ruby -*-
# vi: set ft=ruby :

# # Vagrant 1.7+ automatically inserts a different
# # insecure keypair for each new VM created. The easiest way
# # to use the same keypair for all the machines is to disable
# # this feature and rely on the legacy insecure key.
# # config.ssh.insert_key = false
Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/trusty64"

    # Synced folder configuration 
    if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
        config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
    else
        config.vm.synced_folder ".", "/vagrant"
    end

    # Common domain configuration
    config.vm.provider "virtualbox" do |domain|
	domain.customize ["modifyvm", :id, "--nic2", "hostonly"]
        domain.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet1"]
    end

    # Machine-balancer specific definition
    config.vm.define "identity-balancer" do |vmconfig|
        vmconfig.vm.hostname = "identity-balancer"
        vmconfig.vm.network :private_network, ip: "172.16.76.2", netmask: "28"	# The .1 IP address its often used by router
	vmconfig.vm.network :forwarded_port, host: 8081,  guest: 80 		# This is the HTTPD load balancer VM for this domain 
        vmconfig.vm.network :forwarded_port, host: 10122, guest: 22, id: "ssh"	# This avoid SSH overlaping port in the host 
	vmconfig.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", "2048"]
  	    vbox.customize ["modifyvm", :id, "--name"  , "identity-balancer"]
        end
        vmconfig.vm.provision :shell, path: "balancer-config/bootstrap.sh"	# Install HTTPD and Ansible via shell provisioning
    end

    # Machine-nodes specific definition
    (1..2).each do |i|
	config.vm.define "identity-node#{i}" do |vmconfig|
            vmconfig.vm.hostname = "identity-node#{i}"
            vmconfig.vm.network :private_network, ip: "172.16.76.#{2+i}", netmask: "28"
            vmconfig.vm.network :forwarded_port, host: "818#{i}", guest: 8080  	   	   # Forward to Wildfly application port
 	    vmconfig.vm.network :forwarded_port, host: "919#{i}", guest: 9990              # Forward to Wildfly management port
            vmconfig.vm.network :forwarded_port, host: "1012#{2+i}", guest: 22, id: "ssh"  # This avoid SSH overlaping port in the host
            vmconfig.vm.provider "virtualbox" do |vbox|
            	vbox.customize ["modifyvm", :id, "--memory", "2048"]
            	vbox.customize ["modifyvm", :id, "--name"  , "identity-node#{i}"]
            end
            vmconfig.vm.provision "shell", privileged: false, inline: <<-SHELL
		echo "Installing Open JDK 8 ..."
		sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
		sudo add-apt-repository -y ppa:webupd8team/java
		sudo apt-get update
		sudo apt-get install -y oracle-java8-installer
		sudo rm -rf /var/cache/oracle-jdk8-installer
		export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

		echo "Installing and starting Wildfly App Server 10.0.0.Final ..."
		export WILDFLY_VERSION="10.0.0.Final"
		curl https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz | tar -xz
		sudo mkdir /opt/jboss/
		export JBOSS_HOME="/opt/jboss/wildfly"
		sudo mv wildfly-$WILDFLY_VERSION $JBOSS_HOME
		sudo chown -R vagrant:vagrant $JBOSS_HOME
		$JBOSS_HOME/bin/add-user.sh admin Admin123 --silent
		cp -f /vagrant/nodes-config/standalone-ha.xml $JBOSS_HOME/standalone/configuration/
                cp -r /vagrant/nodes-config/postgresql $JBOSS_HOME/system/layers/base/org/
		IP_ADDR=$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
		sed -i "s|jboss.bind.address.management:127.0.0.1|jboss.bind.address.management:$IP_ADDR|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
		sed -i "s|jboss.bind.address:127.0.0.1|jboss.bind.address:$IP_ADDR|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
		sed -i "s|jboss.bind.address.private:127.0.0.1|jboss.bind.address.private:$IP_ADDR|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
		$JBOSS_HOME/bin/standalone.sh --server-config=standalone-ha.xml -b=0.0.0.0 -bmanagement=$IP_ADDR -Djboss.node.name=identity-node"#{i}"

		echo "Deploying Hiperium Identity Service ..."
		curl -u admin:admin123 -L "http://repository-hiperium.rhcloud.com/service/local/artifact/maven/content?g=com.hiperium&a=hiperium-identity&v=LATEST&p=war&r=snapshots" -o $JBOSS_HOME/standalone/deployments/hiperium-identity.war
            SHELL
        end
    end

    # Put the VM in Vagrant Cache
    if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
    end
end
